[workspace]
members = [
    "dumpster",
    "dumpster_derive",
    "dumpster_test",
    "dumpster_bench",
]
resolver = "2"

[patch.crates-io]
dumpster = { path = "dumpster" }

[profile.release]
lto = true